### ISSUE TITLE
you're awesome

### ISSUE THREAD

**Issue by beeburrt** [prazdevs/zarp-icons#4]
These are great dude! I don't have an issue or a suggestion, I just wanted to express my appreciation.

I'm surprised they aren't more popular. My guess is because the naming puts them at the bottom of the list and maybe people don't search that far down the list?

Actually, I just noticed Zig doesn't have an icon...

Regardless, I love em! Keep up the good work!

**Comment by prazdevs** [comment]
oh thank you :) I actually dont update this one much because i made a port for Cattppuccin theme based on this one.
 If you like the design, you will probably enjoy https://github.com/catppuccin/vscode-icons
It's the same design rules, with the Catppuccin palette (and variants) and many more icons (including Zig)
